language: python

python:
  - 2.7
  - 3.4

virtualenv:
  system_site_packages: true

before_install:
  - "sudo apt-get -qq update"

install:
  - "sudo apt-get install libffi-dev"
  - "sudo pip install --upgrade coverage flake8 cffi pydbus psutil"
  - "sudo make -C codecs install"

script:
  - "flake8 $(find . -iname '*.py')"
  - "nosetests --with-coverage --cover-package=bt_manager tests"

after_success:
  - "coveralls"
